# Generated by Django 6.0.1 on 2026-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('MASALA', 'Masala Chai'), ('GINGER', 'Ginger Chai'), ('ELAICHI', 'Elaichi Chai'), ('GREEN', 'Green Tea'), ('BLACK', 'Black Tea'), ('SPECIAL', 'Special Chai')], default='MASALA', max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chais/')),
                ('rating', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
