# Generated by Django 6.0.1 on 2026-01-19 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaireview_chaistore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chai',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chaireview',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterModelOptions(
            name='chaistore',
            options={'ordering': ['name'], 'verbose_name': 'Chai Store', 'verbose_name_plural': 'Chai Stores'},
        ),
        migrations.AlterUniqueTogether(
            name='chaireview',
            unique_together={('chai', 'user')},
        ),
    ]
